// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class RX_UserInfo
	{
		public string Name{set;get;}
		public int Age{set;get;}
		public int UserID{set;get;}

		public RX_UserInfo ()
		{
		}

		public override string ToString ()
		{
			return LO_XMLTool.Serializer(typeof(RX_UserInfo),this);
		}
	}
}

